<footer>
<div class="firstfooter">
<div class="footer1">
                     <a href="index.php">HOME</a>
                     <a href="product.php">PRODUCT</a>
                     <a href="enquire.php">QUERIES</a>
                     <a href="about.php">ABOUT US</a>
                     <a href="manager.php">MANAGER</a>
                     <a href="enhancements.php">ENHANCEMENT</a>
                     <a href="enhancements2.php">ENHANCEMENT-2</a>
</div>
<div class="snetwork">
                    <p> <a href="https://www.facebook.com/"><img src="images/facebook.png" id="fb" alt="facebook"></a></p>
                    <p> <a href="https://www.twitter.com/"><img src="images/twitter.png" id="twitter" alt="twitter"></a></p>
                    <p> <a href="https://www.instagram.com/"><img src="images/instagram.png" id="instagram" alt="instagram"></a></p>
                    <p><a href="https://www.linkedin.com/"><img src="images/linkedin.png" id="linkedin" alt="linkedin"></a></p>
</div>
 <div class="companyname">
                   <img src="images/LOGO.jpg" id="FI2" alt="balloons">
                   <h1 class="heading2">AISHWARYA'S PARTY EQUIPMENTS</h1>
</div>
</div>
 <div class="lastfooter">
 <div class="copyright">   
                    <p class="copy">
                   &copy;Copyright 2021.All rights reserved.
                    </p>
 </div>
 <div class="legal">
       
                    <p class="copy">      
                 Legal
                   </p>
  </div>
  <div class="privacy">
                   <p class="copy">    
                  Terms and Conditions | Privacy
                   </p>
   </div>
   </div>
    
          </footer>
      
   
  
   
