 <nav class="topnav">
    <br>
                     <a href="index.php">HOME</a>
                     <a href="product.php">PRODUCT</a>
                     <a href="enquire.php">QUERIES</a>
                     <a href="about.php">ABOUT US</a>
                     <a href="manager.php">MANAGER</a>
                     <a href="enhancements.php">ENHANCEMENT</a>
                     <a href="enhancements2.php">ENHANCEMENT-2</a>
              <img src="images/mg.png" id="SEARCH" alt="searchbutton">
              <input type="text"   placeholder=  "   SEARCH...." name="search" id="SBUTTON"/>  
  </nav>             
